### ISSUE TITLE
Añadir función de impresión

### ISSUE THREAD

**Issue by Miguel-Dorta** [nethruster/waReader#1]
Creo que sería útil añadir una función que te dé la capacidad de imprimir la conversación completa con el formato visual que tiene. Por ejemplo, se me ocurre que, al pulsar un botón/icono, se abra la conversación en una nueva pestaña, pero con scroll de tal forma que se pueda imprimir completa la conversación con la función integrada por el navegador. (Es un ejemplo, no estoy seguro de si así se podría llevar a cabo)

**Comment by gariasf** [comment]
Estoy seguro de que se puede hacer algo similar, y me parece una buena idea.
Lo tendré en cuenta.

**Comment by gariasf** [comment]
Funcionalidad implementada desde [ba7b023](https://github.com/nethruster/waReader/commit/ba7b0236b84b41646af10923c9966cc1db1a3d94), gracias por la sugerencia.
