### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by timeakesmarky** [nethruster/waReader#14]
Can you please create a compiled release? :)

**Comment by gariasf** [comment]
Hi @timeakesmarky, we're considering a couple of options. I'll get back to you once we decide on a solution.

I appreciate your patience.

**Comment by gariasf** [comment]
Here you go: [waReader 2.0](https://github.com/nethruster/waReader/releases/tag/2.0.0)

You'll find instructions on how to use it in the description of the release itself. 

If you're going to parse large files (>1 MB) please be patient, depending on your machine it might take a while to load.

Please let me know if you find any issues or questions.

**Comment by timeakesmarky** [comment]
@gariasf I'm getting a page not found error in these addresses.
```
D:\node-v10.5.0-win-x64>hs
Starting up http-server, serving ./
Available on:
  http://192.168.56.1:8080
  http://192.168.224.1:8080
  http://192.168.27.2:8080
  http://192.168.1.104:8080
  http://127.0.0.1:8080
Hit CTRL-C to stop the server
```

**Comment by gariasf** [comment]
You have to use `hs` where you extracted the zip file. Such a folder should have [these](https://i.nth.sh/1BOQ_8TlYx) files. If you extracted the zip at `/home/user/xxx/waReader` then `hs` needs to be called in `/home/user/xxx/waReader`.

You should also be able to use localhost:8080.

**Comment by timeakesmarky** [comment]
I thought so. So, node wasn't in my windows path. I installed node and ran `hs` from wareader folder now but still the same problem.

**Comment by timeakesmarky** [comment]
I tried all addresses:
```
C:\Users\Timea\Desktop\waReader2.0>hs
Starting up http-server, serving ./
Available on:
  http://192.168.56.1:8080
  http://192.168.224.1:8080
  http://192.168.27.2:8080
  http://192.168.1.104:8080
  http://127.0.0.1:8080
Hit CTRL-C to stop the server
```

**Comment by gariasf** [comment]
Can you tell me which browser are you using?

**Comment by timeakesmarky** [comment]
Chrome

**Comment by gariasf** [comment]
Can I see the hs output log in the console?

**Comment by timeakesmarky** [comment]
```
[Sun Sep 08 2019] "GET /" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36"
[Sun Sep 08 2019] "GET /" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36"
[Sun Sep 08 2019] "GET /" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36"
[Sun Sep 08 2019] "GET /" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36"
```

**Comment by gariasf** [comment]
Try using http-server@0.9.0

`npm install -g http-server@0.9.0`

Install it and use it again.

**Comment by timeakesmarky** [comment]
Works now. What was wrong?

**Comment by gariasf** [comment]
It looks like it has to do with the http-server [dependencies causing an infinite redirect](https://github.com/jfhbrook/node-ecstatic/issues/260). It's not a waReader issue. 
For now downgrading the library fixes the problem.

**Comment by timeakesmarky** [comment]
@gariasf Hey, do you know how much of chats whatsapp exports in text format?

**Comment by gariasf** [comment]
Do you mean what might get left out of the exported file?

**Comment by gariasf** [comment]
It is worth mentioning that, according to [official WhatsApp FAQ](https://faq.whatsapp.com/en/android/23756533/):
When exporting with media, you can send up to 10,000 latest messages. Without media, you can send 40,000 messages. These constraints are due to maximum email sizes (because the export might get sent via email).

**Comment by timeakesmarky** [comment]
Yes, my exported chats have only around 37000 messages which is just about a month of chats, from August 1st week. That's too less, I want older chats. I guess there's no way to get those as txt. The only option would be obtaining msgstore.db. I also have this. Is there a way to convert it to whatsapp txt format?

**Comment by gariasf** [comment]
If you want to read msgstore.db you need the encryption key and extra data stored in a different file. I don't think there's any tool to export a "standard" .txt file from those sources.

Searching a bit I found [this](https://github.com/andreas-mausch/whatsapp-viewer). It reads msgstore.db and uses wa.db along with the encryption key to read the messages.

I don't have my phone rooted at the moment and I don't have any intention to, so I can't check if it works properly. 
Their README has more info about the procedure.

**Comment by timeakesmarky** [comment]
Yes, I know about this. It works fine. My phone is old and rooted but I'm looking for txt parsers because I may change my phone and will need a non-root solution. I do have the key and the key file changes sometimes and I would fail to decrypt the crypt12 backups on my new phone.

I found a solution here:
https://android.stackexchange.com/questions/215009/exporting-a-full-whatsapp-chat-to-txt

Look at the answer. It's a paid chrome extension.
https://chrome.google.com/webstore/detail/backup-whatsapp-chats/gmbicfpadlmgkfhfepknbmemfhahelll

**Comment by gariasf** [comment]
That tool scraps the binary chat data from WhatsApp web socket connection. It requires internet connection. However I tested it and it works. 

If you're really interested in using the extension: You can get the downloaded source of the extension from your chrome extension folder (it's JavaScript after all so it not compiled to anything unreadable), tweak the code to, say, avoid taking advantage of license validation and then install it in development mode to use it as your own.

**Comment by timeakesmarky** [comment]
I checked it out, there's a checkLicense.js in its extension folder. I don't know what value to change, I'll trial and error. :D

Yeah, html is fine too as long as I can read it.

But why does it need google account?

**Comment by gariasf** [comment]
Because the license is tied to your google account when you buy the extension at the store. 
I can give you more details in private on how to do what I said, I'm on Twittter and Telegram @gariasf, .
