### ISSUE TITLE
How do I put it to work?

### ISSUE THREAD

**Issue by deriknyvo** [nethruster/waReader#3]
Help me.

**Comment by claudio4** [comment]
Hello deriknyvo!

First of all you need to be sure you are using the 1.0 branch ( the 2.0 branch is under development).
then you just need to run the following commands:
``` bash
# install dependencies
yarn install
# build for production with minification, hashing and autoprefixer
yarn build
```
You will need to start a webserver at the dist folder.

Also you can use instead our live app `https://wareader.nethruster.com/`. waReader runs enterly client-side so, ther is no difference bettewn using it in your own server or in ours,

**Comment by gariasf** [comment]
I'll be closing this issue if there is no further feedback within the next 48h.

**Comment by gariasf** [comment]
> I'll be closing this issue if there is no further feedback within the next 48h.

I'm closing this issue as per my reply.
